<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Donation History</title>
    <style>
        body { 
            font-family: Arial, sans-serif; 
            margin: 20px; 
            line-height: 1.6;
        }
        .header { 
            text-align: center; 
            margin-bottom: 30px; 
            border-bottom: 2px solid #333; 
            padding-bottom: 20px; 
        }
        .user-info { 
            margin-bottom: 20px; 
            background: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
        }
        .summary { 
            background: #f5f5f5; 
            padding: 15px; 
            margin-bottom: 20px; 
            border-radius: 5px; 
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px; 
        }
        th, td { 
            border: 1px solid #ddd; 
            padding: 8px; 
            text-align: left; 
        }
        th { 
            background-color: #f2f2f2; 
            font-weight: bold; 
        }
        .total { 
            font-weight: bold; 
            font-size: 18px; 
            margin-top: 20px; 
            text-align: right; 
            background: #e8f5e8;
            padding: 10px;
            border-radius: 5px;
        }
        .footer { 
            margin-top: 30px; 
            text-align: center; 
            font-size: 12px; 
            color: #666; 
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
        .logo {
            font-size: 24px;
            font-weight: bold;
            color: #00a651;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">UNIFICATION</div>
        <h1>Donation History Report</h1>
        <p>Generated on: <?php echo date('F j, Y \a\t g:i A'); ?></p>
    </div>
    
    <div class="user-info">
        <h3>User Information</h3>
        <p><strong>Name:</strong> <?php echo htmlspecialchars($user['first_name'] . ' ' . $user['last_name']); ?></p>
        <p><strong>Email:</strong> <?php echo htmlspecialchars($user['email']); ?></p>
        <p><strong>User Type:</strong> <?php echo ucfirst(htmlspecialchars($user['user_type'])); ?></p>
    </div>
    
    <div class="summary">
        <h3>Summary</h3>
        <p><strong>Total Donations:</strong> <?php echo $totalDonations; ?></p>
        <p><strong>Total Amount:</strong> ৳<?php echo number_format($totalAmount, 2); ?></p>
    </div>
    
    <h3>Donation Details</h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Request Title</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($donations as $donation): ?>
                <tr>
                    <td><?php echo date('M j, Y', strtotime($donation['created_at'])); ?></td>
                    <td><?php echo htmlspecialchars($donation['title']); ?></td>
                    <td>৳<?php echo number_format($donation['amount'], 2); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    
    <div class="total">
        <p><strong>Total Amount: ৳<?php echo number_format($totalAmount, 2); ?></strong></p>
    </div>
    
    <div class="footer">
        <p>This report was generated by the Unification platform</p>
        <p>Thank you for your generosity and support!</p>
    </div>
</body>
</html>
